apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: demo
    tier: front-end
spec:
  replicas: 4
  selector:
    matchLabels:
      app: demo
      tier: front-end
  template:
    metadata:
      labels:
        app: demo
        tier: front-end
    spec:
      containers:
        - name: nginx
          image: dockeryaswanth/kuberneteslab:v1.0
---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: demo
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
  type: NodePort
