apiVersion: apps/v1
kind: Deployment
metadata:
  name: uat-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: practise-uat  # This is what the Deployment looks for
  template:
    metadata:
      labels:
        app: practise-uat  # Must match selector's app label (changed from 'name: UAT-Deployment')
    spec:
      containers:
        - name: practise-uat  # Better to match container name with app label
          image: dockeryaswanth/kuberneteslab:v1.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: uat-deployment-svc
spec:
  type: NodePort
  selector:
    app: practise-uat
  ports:
  - port: 80
    nodePort: 30002
    targetPort: 80
    protocol: TCP