apiVersion : v1
kind : Pod
metadata: 
  name : pod
  labels: 
    env: prod
    app: nginx
spec:
  containers:
  - name: demo
    image: httpd
    ports:
    - containerPort: 80
---
apiVersion : v1
kind : Service
metadata:
  name : demo-service
spec:
  type: ClusterIP
  selector : 
    app: nginx
  ports: 
    - port: 80
      targetPort: 80
