apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: stage-pod
  name: stage-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: stage-pod
  type: ClusterIP
status:
  loadBalancer: {}
