apiVersion: v1
kind: Service
metadata:
  labels:
    name: stage-pod
  name: stage-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: stage-pod
  type: NodePort
status:
  loadBalancer: {}
